version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp-prod
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
      # Configuración para producción con HTTPS
      # NOTA: Para ejecutar sin certificados inicialmente, cambia las URLs a 'http://'
      # y FORCE_SSL_ADMIN a false. Después de obtener certificados, vuelve a 'https://'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://cms.hotland.com.mx');
        define('WP_SITEURL', 'https://cms.hotland.com.mx');
        define('FORCE_SSL_ADMIN', false);
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', false);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_MEMORY_LIMIT', '512M');
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
        }
        if (isset($$_SERVER['HTTP_X_FORWARDED_HOST'])) {
            $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST'];
        }
    volumes:
      - ./wordpress_files:/var/www/html
    networks:
      - wp_net

  db:
    image: mysql:8.0
    container_name: wp-db
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net

  nginx:
    image: nginx:latest
    container_name: wp-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - wordpress
    networks:
      - wp_net

  certbot:
    image: certbot/certbot
    container_name: wp-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email admin@hotland.com.mx
      --agree-tos
      --no-eff-email
      --non-interactive 
      --force-renewal 
      -d cms.hotland.com.mx"
    networks:
      - wp_net

volumes:
  wordpress_data:
  db_data:

networks:
  wp_net: